version: '3.8'

services:
  nextjs-app:
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_ai
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - PDF_SERVICE_URL=http://pdf-service:8000
    depends_on:
      - db
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next

  pdf-service:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MAIN_SERVICE_ORIGIN_URL=http://localhost:3000
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
    volumes:
      - ./pdf-service:/app
      - pdf-storage:/app/generated_pdfs

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_ai
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  pdf-storage: 